### ISSUE TITLE
Suggestion: copy to clipboard button for column "copy links"

### ISSUE THREAD

**Issue by ErinPo** [christopherldotcom/utm.codes#25]
Something simple like https://github.com/zenorocha/clipboard.js/ could be used and would improve usability as users no longer need to use the keyboard to copy a link to the clipboard.

**Comment by chrislarrycarl** [comment]
Copying to clipboard is easy enough I don't think we'd need an additional library. However, I'm not inclined to automatically copy links on click because not all users have a clipboard manager so I'm not sure I'd want to impose on their clipboard just from a click.

We are selecting the input contents on click so I think that makes it pretty friendly for a keyboard shortcut a copy and paste situation.
